# Generated by Django 6.0.2 on 2026-02-20 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
        ("orders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("condition", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "Damaged Product"),
                            ("WRONG_ITEM", "Wrong Item Sent"),
                            ("MIND_CHANGED", "Mind Changed"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("INCOMPLETE", "Incomplete"),
                    ("QUEUE", "Queue"),
                    ("PROCESSING", "Processing"),
                    ("NO_RESPONSE", "Good But No Response"),
                    ("ON_HOLD", "On Hold"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("PENDING", "Pending"),
                    ("COLLECTING", "Collecting"),
                    ("HOLD_COLLECTING", "Hold (Collecting)"),
                    ("PACKING", "Packing"),
                    ("RTS", "Ready to Ship (RTS)"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("RETURN_REQUEST", "Return Request"),
                    ("PENDING_RETURN", "Pending Return"),
                    ("RETURNED", "Returned"),
                    ("PARTIAL", "Partial Delivery"),
                    ("PENDING_CANCEL", "Pending Cancel"),
                    ("PREORDER", "Preorder"),
                    ("LOST", "Lost"),
                ],
                db_index=True,
                default="INCOMPLETE",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_orde_status_25e057_idx"
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.orderitem"
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="return_requests",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="returnrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="return_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.returnrequest",
            ),
        ),
    ]
