# Generated by Django 6.0.2 on 2026-02-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("BOGO", "Buy One Get One"),
                            ("BUNDLE", "Bundle Discount"),
                            ("TIERED", "Tiered Discount"),
                            ("FLAT", "Flat Discount"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority applies first"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="offers/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logic",
                    models.CharField(
                        choices=[
                            ("MIN_QTY", "Minimum Quantity"),
                            ("MIN_AMOUNT", "Minimum Amount"),
                            ("SPECIFIC_BOOK", "Specific Book"),
                            ("SPECIFIC_CATEGORY", "Specific Category"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_id", models.IntegerField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, help_text="Qty or Amount", max_digits=10
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="promotions.offer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OfferReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("DISCOUNT_PERCENT", "Percentage Discount"),
                            ("DISCOUNT_AMOUNT", "Fixed Amount Discount"),
                            ("FREE_ITEM", "Free Item"),
                            ("FREE_SHIPPING", "Free Shipping"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, help_text="Percent or Amount", max_digits=10
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="promotions.offer",
                    ),
                ),
            ],
        ),
    ]
