# Generated by Django 6.0.2 on 2026-02-20 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_coupon_code_alter_coupon_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilePaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("BKASH", "Bkash"),
                            ("NAGAD", "Nagad"),
                            ("ROCKET", "Rocket"),
                            ("UPAY", "Upay"),
                            ("OTHER", "Other"),
                        ],
                        default="BKASH",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "sender_number",
                    models.CharField(
                        blank=True, help_text="Extracted from SMS", max_length=20
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Extracted Reference",
                        max_length=100,
                    ),
                ),
                ("raw_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_claimed", models.BooleanField(db_index=True, default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional: Number from which money was sent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="mobile_log",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transaction",
                to="payments.mobilepaymentlog",
            ),
        ),
    ]
