# Generated by Django 6.0.2 on 2026-02-19 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("secret_key", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bn_name", models.CharField(blank=True, max_length=100)),
                ("url", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Inside Dhaka, Sub Dhaka, Outside Dhaka",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bn_name", models.CharField(blank=True, max_length=100)),
                ("lat", models.CharField(blank=True, max_length=100)),
                ("lon", models.CharField(blank=True, max_length=100)),
                ("url", models.CharField(blank=True, max_length=100)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.division",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Maximum weight in KG for this rate",
                        max_digits=6,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="logistics.shippingzone",
                    ),
                ),
            ],
            options={
                "ordering": ["max_weight"],
            },
        ),
        migrations.CreateModel(
            name="OverweightCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apply_above_weight",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Apply this rule if weight is above this value (KG)",
                        max_digits=6,
                    ),
                ),
                (
                    "charge_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Additional charge per unit weight",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        help_text="Unit weight for the additional charge (e.g. 1kg)",
                        max_digits=6,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overweight_charges",
                        to="logistics.shippingzone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bn_name", models.CharField(blank=True, max_length=100)),
                ("url", models.CharField(blank=True, max_length=100)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.district",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thanas",
                        to="logistics.shippingzone",
                    ),
                ),
            ],
        ),
    ]
