# Generated by Django 6.0.2 on 2026-02-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True, max_length=15, unique=True, verbose_name="phone number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("CUSTOMER", "Customer"),
                    ("COLLECTOR", "Collector"),
                    ("PACKER", "Packer"),
                    ("COURIER_MANAGER", "Courier Manager"),
                ],
                db_index=True,
                default="CUSTOMER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.usertag"
            ),
        ),
    ]
